### ISSUE TITLE
[NEW USER] guilherme

### ISSUE THREAD

**Issue by Hugemiler** [Klepac-Ceraj-Lab/klepac-ceraj-lab.github.io#7]
### Your name

Guilherme Zainotti Miguel Fahur Bottino

### Your Wellesley e-mail address

gz101@wellesley.edu

### Requested user name

guilherme

### Which server(s) do you need access to?

- [X] hopper
- [X] ada
- [ ] rosalind
- [ ] one of the Raspberry pis

### ssh-keys

```Text
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJhk0IqqWVvha5LL1AsvSb1bgwDvPmn4+Zn9JSo0BtJUqjCUSQzSSZO23EyS5OyqClj9U4qGADg7mtrF/GwzQR9lvAWgQPiFGs/AE5bCM6ikAlBc7XUITwXdjRBmxhLIjohPNLKupGZUCWSieSPGQXvoxcZiVnXaoj7wYsHK18udsPEfwXKo+IANfscPhIH41Hz8jZDonAfuhyeHM6osrTjxR5cn4ZiQXgazxDoXAvvipyvPUTZDDFfGG8lf0HOKRUGxy0gNFpkZ+tx+pUX7yxVKQxXY949rPg0k3ewq0nfVtu1DtAtSzDzsNhdPbz/BkMEgbEmwQKn4Jdq2HsuWHe1GRSvGeriog6tig67GRyHRlK91HM2iV1dBbiuGCcrOr8tMLcKJp3iAwhoubQHtv11OTRVyueaDYJQafJHu5Yr6c4TGgth+wyJEhblot50y+KPNE+L6lPdaUlGfxD3GRpAqTfd3HCo72tOYoKH06jMtYgYzojzEB9CWBzVFx8BCk= guilherme@guilherme-popos
```

**Comment by kescobo** [comment]
@Hugemiler For now I'm just going to give you access to `ada` and `hopper`. If at some future date it makes sense for you to be on `rosalind`, we can always add it.

**Comment by kescobo** [comment]
I've set up your logins to both `ada` and `hopper`. Let me know if you have any issues connecting. Note that you need to be connected to Wellesely Secure wifi XOR connected to VPN in order to find the computers on the network. If you try to do both, things will get wonky.

I will send you the current password over slack, and I would change it first thing (`passwd`), but it shouldn't actually matter because password login is disabled and I haven't given you sudo.
